"""empty message

Revision ID: 2f1eec43ae6a
Revises: 7d80d31666bb
Create Date: 2020-05-18 16:09:39.368512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1eec43ae6a'
down_revision = '7d80d31666bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dos_db')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dos_db',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ip_addr', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
